using System.Reflection;
using System.Text;

namespace NetFxProxy.Generator;

public class ProxyEmitter
{
    private readonly TypeClassifier _classifier;

    public ProxyEmitter(TypeClassifier classifier)
    {
        _classifier = classifier;
    }

    public string Emit(AnalyzedType analyzed)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by NetFxProxy.Generator - do not edit.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using NetFxProxy.Runtime;");
        sb.AppendLine();

        string ns = analyzed.Type.Namespace ?? "";
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        if (analyzed.IsException)
            EmitExceptionType(sb, analyzed);
        else if (analyzed.IsStatic)
            EmitStaticType(sb, analyzed);
        else
            EmitInstanceType(sb, analyzed);

        return sb.ToString();
    }

    private void EmitStaticType(StringBuilder sb, AnalyzedType analyzed)
    {
        sb.AppendLine($"public static class {analyzed.Type.Name}");
        sb.AppendLine("{");
        sb.AppendLine("    private static int? _typeHandle;");
        sb.AppendLine(
            $"    private static int TypeHandle => _typeHandle ??= NetFxBridge.Instance.ResolveType(\"{analyzed.AssemblyFileName}\", \"{analyzed.FullName}\");"
        );
        sb.AppendLine();

        HashSet<string> sigs = new HashSet<string>();
        foreach (MethodInfo method in analyzed.Methods.Where(m => m.IsStatic))
        {
            if (sigs.Add(GetMethodSig(method)))
                EmitMethod(sb, method, analyzed, isStatic: true);
        }

        sb.AppendLine("}");
    }

    private void EmitInstanceType(StringBuilder sb, AnalyzedType analyzed)
    {
        sb.AppendLine($"public sealed class {analyzed.Type.Name} : global::System.IDisposable");
        sb.AppendLine("{");
        sb.AppendLine("    private static int? _typeHandle;");
        sb.AppendLine(
            $"    private static int TypeHandle => _typeHandle ??= NetFxBridge.Instance.ResolveType(\"{analyzed.AssemblyFileName}\", \"{analyzed.FullName}\");"
        );
        sb.AppendLine();
        sb.AppendLine("    internal NetFxObjectHandle Handle { get; }");
        sb.AppendLine();
        sb.AppendLine(
            $"    internal {analyzed.Type.Name}(NetFxObjectHandle handle) {{ Handle = handle; }}"
        );
        sb.AppendLine();

        HashSet<string> ctorSigs = new HashSet<string> { "NetFxProxy.Runtime.NetFxObjectHandle" };
        foreach (ConstructorInfo ctor in analyzed.Constructors)
        {
            string sig = GetCtorSig(ctor);
            if (ctorSigs.Add(sig))
                EmitConstructor(sb, ctor, analyzed);
        }

        HashSet<string> propNames = new HashSet<string>();
        foreach (PropertyInfo prop in analyzed.Properties)
        {
            if (propNames.Add(prop.Name))
                EmitProperty(sb, prop, analyzed);
        }

        HashSet<string> methodSigs = new HashSet<string>();
        foreach (MethodInfo method in analyzed.Methods.Where(m => !m.IsStatic))
        {
            if (methodSigs.Add(GetMethodSig(method)))
                EmitMethod(sb, method, analyzed, isStatic: false);
        }
        foreach (MethodInfo method in analyzed.Methods.Where(m => m.IsStatic))
        {
            if (methodSigs.Add("static:" + GetMethodSig(method)))
                EmitMethod(sb, method, analyzed, isStatic: true);
        }

        sb.AppendLine("    public void Dispose() => Handle.Dispose();");

        sb.AppendLine("}");
    }

    private void EmitExceptionType(StringBuilder sb, AnalyzedType analyzed)
    {
        sb.AppendLine($"public sealed class {analyzed.Type.Name} : global::System.Exception");
        sb.AppendLine("{");
        sb.AppendLine("    internal NetFxObjectHandle Handle { get; }");
        sb.AppendLine();
        sb.AppendLine($"    internal {analyzed.Type.Name}(NetFxObjectHandle handle)");
        sb.AppendLine(
            "        : base(handle.GetProperty(\"Message\").AsString() ?? \"Unknown error\")"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        Handle = handle;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private void EmitConstructor(StringBuilder sb, ConstructorInfo ctor, AnalyzedType analyzed)
    {
        ParameterInfo[] parms = ctor.GetParameters();
        if (parms.Any(p => !_classifier.CanMarshalParameter(p.ParameterType)))
            return;

        string paramList = FormatParamList(parms);
        string argList = FormatArgList(parms);
        string argExpr = argList.Length > 0 ? ", " + argList : "";

        sb.AppendLine($"    public {analyzed.Type.Name}({paramList})");
        sb.AppendLine($"        : this(NetFxBridge.Instance.CreateInstance(TypeHandle{argExpr}))");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void EmitProperty(StringBuilder sb, PropertyInfo prop, AnalyzedType analyzed)
    {
        TypeKind kind = _classifier.Classify(prop.PropertyType);
        string typeName = _classifier.GetCSharpType(prop.PropertyType);

        sb.AppendLine($"    public {typeName} {prop.Name}");
        sb.AppendLine("    {");

        if (prop.CanRead)
        {
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            NetFxResult __r = NetFxBridge.Instance.GetProperty(Handle, \"{prop.Name}\");"
            );
            EmitReturnConversion(sb, prop.PropertyType, "__r", "            ");
            sb.AppendLine("        }");
        }

        if (prop.CanWrite)
        {
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            string argFactory = _classifier.GetArgFactory(prop.PropertyType);
            string valueExpr =
                kind == TypeKind.Generated ? $"{argFactory}(value.Handle)" : $"{argFactory}(value)";
            sb.AppendLine(
                $"            NetFxBridge.Instance.SetProperty(Handle, \"{prop.Name}\", {valueExpr});"
            );
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void EmitMethod(
        StringBuilder sb,
        MethodInfo method,
        AnalyzedType analyzed,
        bool isStatic
    )
    {
        ParameterInfo[] parms = method.GetParameters();
        if (parms.Any(p => !_classifier.CanMarshalParameter(p.ParameterType)))
            return;

        bool hasRefs = parms.Any(p => p.ParameterType.IsByRef);
        string returnType = _classifier.GetCSharpType(method.ReturnType);
        string paramList = FormatParamList(parms);
        string staticMod = isStatic ? "static " : "";

        sb.AppendLine($"    public {staticMod}{returnType} {method.Name}({paramList})");
        sb.AppendLine("    {");

        foreach (ParameterInfo p in parms)
        {
            if (p.IsOut)
            {
                string pName = SafeName(p.Name!);
                sb.AppendLine($"        {pName} = default!;");
            }
        }

        if (parms.Length > 0)
        {
            sb.AppendLine("        NetFxArg[] __args = new NetFxArg[]");
            sb.AppendLine("        {");
            foreach (ParameterInfo p in parms)
                sb.AppendLine($"            {FormatSingleArg(p)},");
            sb.AppendLine("        };");
        }

        string argsExpr = parms.Length > 0 ? "__args" : "global::System.Array.Empty<NetFxArg>()";
        string target = isStatic ? "TypeHandle" : "Handle";
        TypeKind returnKind = _classifier.Classify(method.ReturnType);

        if (hasRefs && !isStatic)
        {
            sb.AppendLine(
                $"        NetFxResult __r = NetFxBridge.Instance.InvokeInstanceWithRefs({target}, \"{method.Name}\", {argsExpr}, out NetFxResult[] __refs);"
            );
            EmitRefWritebacks(sb, parms);
        }
        else
        {
            string invokeMethod = isStatic ? "InvokeStatic" : "InvokeInstance";
            sb.AppendLine(
                $"        NetFxResult __r = NetFxBridge.Instance.{invokeMethod}({target}, \"{method.Name}\", {argsExpr});"
            );
        }

        string retFullName = method.ReturnType.FullName ?? "";
        if (returnKind == TypeKind.Void || retFullName == "System.Void") { }
        else
        {
            EmitReturnConversion(sb, method.ReturnType, "__r", "        ");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void EmitReturnConversion(
        StringBuilder sb,
        Type returnType,
        string resultVar,
        string indent
    )
    {
        TypeKind kind = _classifier.Classify(returnType);

        if (kind == TypeKind.Generated)
        {
            string typeName = _classifier.GetCSharpType(returnType);
            sb.AppendLine($"{indent}return new {typeName}({resultVar}.ToHandle());");
        }
        else if (kind == TypeKind.Marshaled)
        {
            MarshalConfig? config = _classifier.GetMarshalConfig(returnType);
            if (
                config != null
                && config.Strategy == "connectionString"
                && config.ExtractProperty != null
            )
            {
                sb.AppendLine(
                    $"{indent}using (NetFxObjectHandle __handle = {resultVar}.ToHandle())"
                );
                sb.AppendLine($"{indent}{{");
                sb.AppendLine(
                    $"{indent}    string __connStr = __handle.GetProperty(\"{config.ExtractProperty}\").AsString()!;"
                );
                sb.AppendLine(
                    $"{indent}    {config.Net10Type} __obj = new {config.Net10Type}(__connStr);"
                );
                sb.AppendLine($"{indent}    __obj.Open();");
                sb.AppendLine($"{indent}    return __obj;");
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                string cast = _classifier.GetNarrowingCast(returnType);
                string extractor = _classifier.GetResultExtractor(returnType);
                sb.AppendLine($"{indent}return {cast}{resultVar}{extractor};");
            }
        }
        else
        {
            string cast = _classifier.GetNarrowingCast(returnType);
            string extractor = _classifier.GetResultExtractor(returnType);
            sb.AppendLine($"{indent}return {cast}{resultVar}{extractor};");
        }
    }

    private void EmitRefWritebacks(StringBuilder sb, ParameterInfo[] parms)
    {
        for (int i = 0; i < parms.Length; i++)
        {
            ParameterInfo p = parms[i];
            if (!p.ParameterType.IsByRef)
                continue;

            Type elementType = p.ParameterType.GetElementType()!;
            TypeKind kind = _classifier.Classify(elementType);
            string pName = SafeName(p.Name!);

            if (kind == TypeKind.Generated)
            {
                string typeName = _classifier.GetCSharpType(elementType);
                bool isException = false;
                try
                {
                    isException = _classifier.IsExceptionType(elementType);
                }
                catch { }

                sb.AppendLine($"        if (__refs[{i}].Type != -1 && !__refs[{i}].IsNull)");
                sb.AppendLine($"            {pName} = new {typeName}(__refs[{i}].ToHandle());");
            }
            else if (kind == TypeKind.Opaque)
            {
                sb.AppendLine($"        if (__refs[{i}].Type != -1 && !__refs[{i}].IsNull)");
                sb.AppendLine($"            {pName} = __refs[{i}].ToHandle();");
            }
        }
    }

    private string FormatParamList(ParameterInfo[] parms)
    {
        return string.Join(
            ", ",
            parms.Select(p =>
            {
                string mod = p.ParameterType.IsByRef ? (p.IsOut ? "out " : "ref ") : "";
                string typeName = _classifier.GetCSharpType(p.ParameterType);
                bool isNullableRef =
                    p.ParameterType.IsByRef
                    && _classifier.Classify(p.ParameterType) == TypeKind.Generated;
                return $"{mod}{typeName}{(isNullableRef ? "?" : "")} {SafeName(p.Name!)}";
            })
        );
    }

    private string FormatArgList(ParameterInfo[] parms)
    {
        return string.Join(", ", parms.Select(p => FormatSingleArg(p)));
    }

    private string FormatSingleArg(ParameterInfo p)
    {
        TypeKind kind = _classifier.Classify(p.ParameterType);
        string pName = SafeName(p.Name!);

        if (p.ParameterType.IsByRef)
        {
            Type elementType = p.ParameterType.GetElementType()!;
            TypeKind elementKind = _classifier.Classify(elementType);
            if (elementKind == TypeKind.Generated)
            {
                return $"NetFxArg.RefHandle({pName}?.Handle)";
            }
            if (elementKind == TypeKind.Opaque)
                return $"NetFxArg.RefHandle({pName})";
            return "NetFxArg.RefNull()";
        }

        string factory = _classifier.GetArgFactory(p.ParameterType);

        if (kind == TypeKind.Generated)
            return $"{factory}({pName}.Handle)";

        return $"{factory}({pName})";
    }

    private string GetMethodSig(MethodInfo method)
    {
        string paramSig = string.Join(
            ",",
            method.GetParameters().Select(p => _classifier.GetCSharpType(p.ParameterType))
        );
        return $"{method.Name}({paramSig})";
    }

    private string GetCtorSig(ConstructorInfo ctor)
    {
        return string.Join(
            ",",
            ctor.GetParameters().Select(p => _classifier.GetCSharpType(p.ParameterType))
        );
    }

    private static string SafeName(string name) =>
        name switch
        {
            "class"
            or "event"
            or "object"
            or "string"
            or "int"
            or "long"
            or "bool"
            or "double"
            or "float"
            or "decimal"
            or "ref"
            or "out"
            or "params"
            or "operator"
            or "base"
            or "this"
            or "new"
            or "default" => $"@{name}",
            _ => name,
        };
}
